// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meet_msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "meet_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace pms {

void protobuf_ShutdownFile_meet_5fmsg_2eproto() {
  delete Login::default_instance_;
  delete Logout::default_instance_;
  delete Keep::default_instance_;
  delete MeetMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_meet_5fmsg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_meet_5fmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::pms::protobuf_AddDesc_common_5fmsg_2eproto();
  ::pms::protobuf_AddDesc_meet_5fmsg_5ftype_2eproto();
  Login::default_instance_ = new Login();
  Logout::default_instance_ = new Logout();
  Keep::default_instance_ = new Keep();
  MeetMsg::default_instance_ = new MeetMsg();
  Login::default_instance_->InitAsDefaultInstance();
  Logout::default_instance_->InitAsDefaultInstance();
  Keep::default_instance_->InitAsDefaultInstance();
  MeetMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_meet_5fmsg_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_meet_5fmsg_2eproto_once_);
void protobuf_AddDesc_meet_5fmsg_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_meet_5fmsg_2eproto_once_,
                 &protobuf_AddDesc_meet_5fmsg_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_meet_5fmsg_2eproto {
  StaticDescriptorInitializer_meet_5fmsg_2eproto() {
    protobuf_AddDesc_meet_5fmsg_2eproto();
  }
} static_descriptor_initializer_meet_5fmsg_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Login::kUsrFromFieldNumber;
const int Login::kUsrTokenFieldNumber;
const int Login::kUsrNnameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Login::Login()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pms.Login)
}

void Login::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Login::Login(const Login& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pms.Login)
}

void Login::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  usr_from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_nname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Login::~Login() {
  // @@protoc_insertion_point(destructor:pms.Login)
  SharedDtor();
}

void Login::SharedDtor() {
  usr_from_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_nname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Login::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Login& Login::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_meet_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_meet_5fmsg_2eproto();
#endif
  return *default_instance_;
}

Login* Login::default_instance_ = NULL;

Login* Login::New(::google::protobuf::Arena* arena) const {
  Login* n = new Login;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Login::Clear() {
// @@protoc_insertion_point(message_clear_start:pms.Login)
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_nname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Login::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pms.Login)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string usr_from = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_from()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_from().data(), this->usr_from().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.Login.usr_from"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_usr_token;
        break;
      }

      // optional string usr_token = 2;
      case 2: {
        if (tag == 18) {
         parse_usr_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_token().data(), this->usr_token().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.Login.usr_token"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_usr_nname;
        break;
      }

      // optional string usr_nname = 3;
      case 3: {
        if (tag == 26) {
         parse_usr_nname:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_nname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_nname().data(), this->usr_nname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.Login.usr_nname"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pms.Login)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pms.Login)
  return false;
#undef DO_
}

void Login::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pms.Login)
  // optional string usr_from = 1;
  if (this->usr_from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_from().data(), this->usr_from().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.Login.usr_from");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->usr_from(), output);
  }

  // optional string usr_token = 2;
  if (this->usr_token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_token().data(), this->usr_token().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.Login.usr_token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->usr_token(), output);
  }

  // optional string usr_nname = 3;
  if (this->usr_nname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_nname().data(), this->usr_nname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.Login.usr_nname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->usr_nname(), output);
  }

  // @@protoc_insertion_point(serialize_end:pms.Login)
}

int Login::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pms.Login)
  int total_size = 0;

  // optional string usr_from = 1;
  if (this->usr_from().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_from());
  }

  // optional string usr_token = 2;
  if (this->usr_token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_token());
  }

  // optional string usr_nname = 3;
  if (this->usr_nname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_nname());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Login::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Login*>(&from));
}

void Login::MergeFrom(const Login& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pms.Login)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.usr_from().size() > 0) {

    usr_from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_from_);
  }
  if (from.usr_token().size() > 0) {

    usr_token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_token_);
  }
  if (from.usr_nname().size() > 0) {

    usr_nname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_nname_);
  }
}

void Login::CopyFrom(const Login& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pms.Login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Login::IsInitialized() const {

  return true;
}

void Login::Swap(Login* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Login::InternalSwap(Login* other) {
  usr_from_.Swap(&other->usr_from_);
  usr_token_.Swap(&other->usr_token_);
  usr_nname_.Swap(&other->usr_nname_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string Login::GetTypeName() const {
  return "pms.Login";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Login

// optional string usr_from = 1;
void Login::clear_usr_from() {
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Login::usr_from() const {
  // @@protoc_insertion_point(field_get:pms.Login.usr_from)
  return usr_from_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Login::set_usr_from(const ::std::string& value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.Login.usr_from)
}
 void Login::set_usr_from(const char* value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.Login.usr_from)
}
 void Login::set_usr_from(const char* value, size_t size) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.Login.usr_from)
}
 ::std::string* Login::mutable_usr_from() {
  
  // @@protoc_insertion_point(field_mutable:pms.Login.usr_from)
  return usr_from_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Login::release_usr_from() {
  // @@protoc_insertion_point(field_release:pms.Login.usr_from)
  
  return usr_from_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Login::set_allocated_usr_from(::std::string* usr_from) {
  if (usr_from != NULL) {
    
  } else {
    
  }
  usr_from_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_from);
  // @@protoc_insertion_point(field_set_allocated:pms.Login.usr_from)
}

// optional string usr_token = 2;
void Login::clear_usr_token() {
  usr_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Login::usr_token() const {
  // @@protoc_insertion_point(field_get:pms.Login.usr_token)
  return usr_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Login::set_usr_token(const ::std::string& value) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.Login.usr_token)
}
 void Login::set_usr_token(const char* value) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.Login.usr_token)
}
 void Login::set_usr_token(const char* value, size_t size) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.Login.usr_token)
}
 ::std::string* Login::mutable_usr_token() {
  
  // @@protoc_insertion_point(field_mutable:pms.Login.usr_token)
  return usr_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Login::release_usr_token() {
  // @@protoc_insertion_point(field_release:pms.Login.usr_token)
  
  return usr_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Login::set_allocated_usr_token(::std::string* usr_token) {
  if (usr_token != NULL) {
    
  } else {
    
  }
  usr_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_token);
  // @@protoc_insertion_point(field_set_allocated:pms.Login.usr_token)
}

// optional string usr_nname = 3;
void Login::clear_usr_nname() {
  usr_nname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Login::usr_nname() const {
  // @@protoc_insertion_point(field_get:pms.Login.usr_nname)
  return usr_nname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Login::set_usr_nname(const ::std::string& value) {
  
  usr_nname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.Login.usr_nname)
}
 void Login::set_usr_nname(const char* value) {
  
  usr_nname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.Login.usr_nname)
}
 void Login::set_usr_nname(const char* value, size_t size) {
  
  usr_nname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.Login.usr_nname)
}
 ::std::string* Login::mutable_usr_nname() {
  
  // @@protoc_insertion_point(field_mutable:pms.Login.usr_nname)
  return usr_nname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Login::release_usr_nname() {
  // @@protoc_insertion_point(field_release:pms.Login.usr_nname)
  
  return usr_nname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Login::set_allocated_usr_nname(::std::string* usr_nname) {
  if (usr_nname != NULL) {
    
  } else {
    
  }
  usr_nname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_nname);
  // @@protoc_insertion_point(field_set_allocated:pms.Login.usr_nname)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Logout::kUsrFromFieldNumber;
const int Logout::kUsrTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Logout::Logout()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pms.Logout)
}

void Logout::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Logout::Logout(const Logout& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pms.Logout)
}

void Logout::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  usr_from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Logout::~Logout() {
  // @@protoc_insertion_point(destructor:pms.Logout)
  SharedDtor();
}

void Logout::SharedDtor() {
  usr_from_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Logout::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Logout& Logout::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_meet_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_meet_5fmsg_2eproto();
#endif
  return *default_instance_;
}

Logout* Logout::default_instance_ = NULL;

Logout* Logout::New(::google::protobuf::Arena* arena) const {
  Logout* n = new Logout;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Logout::Clear() {
// @@protoc_insertion_point(message_clear_start:pms.Logout)
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Logout::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pms.Logout)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string usr_from = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_from()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_from().data(), this->usr_from().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.Logout.usr_from"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_usr_token;
        break;
      }

      // optional string usr_token = 2;
      case 2: {
        if (tag == 18) {
         parse_usr_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_token().data(), this->usr_token().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.Logout.usr_token"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pms.Logout)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pms.Logout)
  return false;
#undef DO_
}

void Logout::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pms.Logout)
  // optional string usr_from = 1;
  if (this->usr_from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_from().data(), this->usr_from().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.Logout.usr_from");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->usr_from(), output);
  }

  // optional string usr_token = 2;
  if (this->usr_token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_token().data(), this->usr_token().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.Logout.usr_token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->usr_token(), output);
  }

  // @@protoc_insertion_point(serialize_end:pms.Logout)
}

int Logout::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pms.Logout)
  int total_size = 0;

  // optional string usr_from = 1;
  if (this->usr_from().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_from());
  }

  // optional string usr_token = 2;
  if (this->usr_token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_token());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Logout::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Logout*>(&from));
}

void Logout::MergeFrom(const Logout& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pms.Logout)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.usr_from().size() > 0) {

    usr_from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_from_);
  }
  if (from.usr_token().size() > 0) {

    usr_token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_token_);
  }
}

void Logout::CopyFrom(const Logout& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pms.Logout)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Logout::IsInitialized() const {

  return true;
}

void Logout::Swap(Logout* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Logout::InternalSwap(Logout* other) {
  usr_from_.Swap(&other->usr_from_);
  usr_token_.Swap(&other->usr_token_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string Logout::GetTypeName() const {
  return "pms.Logout";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Logout

// optional string usr_from = 1;
void Logout::clear_usr_from() {
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Logout::usr_from() const {
  // @@protoc_insertion_point(field_get:pms.Logout.usr_from)
  return usr_from_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Logout::set_usr_from(const ::std::string& value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.Logout.usr_from)
}
 void Logout::set_usr_from(const char* value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.Logout.usr_from)
}
 void Logout::set_usr_from(const char* value, size_t size) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.Logout.usr_from)
}
 ::std::string* Logout::mutable_usr_from() {
  
  // @@protoc_insertion_point(field_mutable:pms.Logout.usr_from)
  return usr_from_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Logout::release_usr_from() {
  // @@protoc_insertion_point(field_release:pms.Logout.usr_from)
  
  return usr_from_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Logout::set_allocated_usr_from(::std::string* usr_from) {
  if (usr_from != NULL) {
    
  } else {
    
  }
  usr_from_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_from);
  // @@protoc_insertion_point(field_set_allocated:pms.Logout.usr_from)
}

// optional string usr_token = 2;
void Logout::clear_usr_token() {
  usr_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Logout::usr_token() const {
  // @@protoc_insertion_point(field_get:pms.Logout.usr_token)
  return usr_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Logout::set_usr_token(const ::std::string& value) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.Logout.usr_token)
}
 void Logout::set_usr_token(const char* value) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.Logout.usr_token)
}
 void Logout::set_usr_token(const char* value, size_t size) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.Logout.usr_token)
}
 ::std::string* Logout::mutable_usr_token() {
  
  // @@protoc_insertion_point(field_mutable:pms.Logout.usr_token)
  return usr_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Logout::release_usr_token() {
  // @@protoc_insertion_point(field_release:pms.Logout.usr_token)
  
  return usr_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Logout::set_allocated_usr_token(::std::string* usr_token) {
  if (usr_token != NULL) {
    
  } else {
    
  }
  usr_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_token);
  // @@protoc_insertion_point(field_set_allocated:pms.Logout.usr_token)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Keep::kUsrFromFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Keep::Keep()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pms.Keep)
}

void Keep::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Keep::Keep(const Keep& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pms.Keep)
}

void Keep::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  usr_from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Keep::~Keep() {
  // @@protoc_insertion_point(destructor:pms.Keep)
  SharedDtor();
}

void Keep::SharedDtor() {
  usr_from_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Keep::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Keep& Keep::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_meet_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_meet_5fmsg_2eproto();
#endif
  return *default_instance_;
}

Keep* Keep::default_instance_ = NULL;

Keep* Keep::New(::google::protobuf::Arena* arena) const {
  Keep* n = new Keep;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Keep::Clear() {
// @@protoc_insertion_point(message_clear_start:pms.Keep)
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Keep::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pms.Keep)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string usr_from = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_from()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_from().data(), this->usr_from().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.Keep.usr_from"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pms.Keep)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pms.Keep)
  return false;
#undef DO_
}

void Keep::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pms.Keep)
  // optional string usr_from = 1;
  if (this->usr_from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_from().data(), this->usr_from().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.Keep.usr_from");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->usr_from(), output);
  }

  // @@protoc_insertion_point(serialize_end:pms.Keep)
}

int Keep::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pms.Keep)
  int total_size = 0;

  // optional string usr_from = 1;
  if (this->usr_from().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_from());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Keep::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Keep*>(&from));
}

void Keep::MergeFrom(const Keep& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pms.Keep)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.usr_from().size() > 0) {

    usr_from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_from_);
  }
}

void Keep::CopyFrom(const Keep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pms.Keep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Keep::IsInitialized() const {

  return true;
}

void Keep::Swap(Keep* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Keep::InternalSwap(Keep* other) {
  usr_from_.Swap(&other->usr_from_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string Keep::GetTypeName() const {
  return "pms.Keep";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Keep

// optional string usr_from = 1;
void Keep::clear_usr_from() {
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Keep::usr_from() const {
  // @@protoc_insertion_point(field_get:pms.Keep.usr_from)
  return usr_from_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Keep::set_usr_from(const ::std::string& value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.Keep.usr_from)
}
 void Keep::set_usr_from(const char* value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.Keep.usr_from)
}
 void Keep::set_usr_from(const char* value, size_t size) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.Keep.usr_from)
}
 ::std::string* Keep::mutable_usr_from() {
  
  // @@protoc_insertion_point(field_mutable:pms.Keep.usr_from)
  return usr_from_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Keep::release_usr_from() {
  // @@protoc_insertion_point(field_release:pms.Keep.usr_from)
  
  return usr_from_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Keep::set_allocated_usr_from(::std::string* usr_from) {
  if (usr_from != NULL) {
    
  } else {
    
  }
  usr_from_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_from);
  // @@protoc_insertion_point(field_set_allocated:pms.Keep.usr_from)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MeetMsg::kMsgHeadFieldNumber;
const int MeetMsg::kMsgTagFieldNumber;
const int MeetMsg::kMsgTypeFieldNumber;
const int MeetMsg::kUsrFromFieldNumber;
const int MeetMsg::kMsgContFieldNumber;
const int MeetMsg::kRomIdFieldNumber;
const int MeetMsg::kRomNameFieldNumber;
const int MeetMsg::kNckNameFieldNumber;
const int MeetMsg::kUsrTokenFieldNumber;
const int MeetMsg::kMsgSeqsFieldNumber;
const int MeetMsg::kMemNumFieldNumber;
const int MeetMsg::kUsrTotoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MeetMsg::MeetMsg()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pms.MeetMsg)
}

void MeetMsg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  usr_toto_ = const_cast< ::pms::ToUser*>(
      ::pms::ToUser::internal_default_instance());
#else
  usr_toto_ = const_cast< ::pms::ToUser*>(&::pms::ToUser::default_instance());
#endif
}

MeetMsg::MeetMsg(const MeetMsg& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pms.MeetMsg)
}

void MeetMsg::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  msg_head_ = 0;
  msg_tag_ = 0;
  msg_type_ = 0;
  usr_from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_cont_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rom_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rom_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nck_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_seqs_ = GOOGLE_LONGLONG(0);
  mem_num_ = 0;
  usr_toto_ = NULL;
}

MeetMsg::~MeetMsg() {
  // @@protoc_insertion_point(destructor:pms.MeetMsg)
  SharedDtor();
}

void MeetMsg::SharedDtor() {
  usr_from_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_cont_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rom_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rom_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nck_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete usr_toto_;
  }
}

void MeetMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MeetMsg& MeetMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_meet_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_meet_5fmsg_2eproto();
#endif
  return *default_instance_;
}

MeetMsg* MeetMsg::default_instance_ = NULL;

MeetMsg* MeetMsg::New(::google::protobuf::Arena* arena) const {
  MeetMsg* n = new MeetMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MeetMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:pms.MeetMsg)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MeetMsg, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MeetMsg*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(msg_head_, msg_tag_);
  msg_type_ = 0;
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_cont_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rom_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rom_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nck_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usr_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_seqs_ = GOOGLE_LONGLONG(0);
  mem_num_ = 0;
  if (GetArenaNoVirtual() == NULL && usr_toto_ != NULL) delete usr_toto_;
  usr_toto_ = NULL;

#undef ZR_HELPER_
#undef ZR_

}

bool MeetMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pms.MeetMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .pms.EMsgHead msg_head = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_msg_head(static_cast< ::pms::EMsgHead >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_msg_tag;
        break;
      }

      // optional .pms.EMsgTag msg_tag = 2;
      case 2: {
        if (tag == 16) {
         parse_msg_tag:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_msg_tag(static_cast< ::pms::EMsgTag >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_msg_type;
        break;
      }

      // optional .pms.EMsgType msg_type = 3;
      case 3: {
        if (tag == 24) {
         parse_msg_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_msg_type(static_cast< ::pms::EMsgType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_usr_from;
        break;
      }

      // optional string usr_from = 4;
      case 4: {
        if (tag == 34) {
         parse_usr_from:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_from()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_from().data(), this->usr_from().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.MeetMsg.usr_from"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_msg_cont;
        break;
      }

      // optional string msg_cont = 5;
      case 5: {
        if (tag == 42) {
         parse_msg_cont:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg_cont()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg_cont().data(), this->msg_cont().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.MeetMsg.msg_cont"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_rom_id;
        break;
      }

      // optional string rom_id = 6;
      case 6: {
        if (tag == 50) {
         parse_rom_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rom_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->rom_id().data(), this->rom_id().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.MeetMsg.rom_id"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_rom_name;
        break;
      }

      // optional string rom_name = 7;
      case 7: {
        if (tag == 58) {
         parse_rom_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rom_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->rom_name().data(), this->rom_name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.MeetMsg.rom_name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_nck_name;
        break;
      }

      // optional string nck_name = 8;
      case 8: {
        if (tag == 66) {
         parse_nck_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nck_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nck_name().data(), this->nck_name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.MeetMsg.nck_name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_usr_token;
        break;
      }

      // optional string usr_token = 9;
      case 9: {
        if (tag == 74) {
         parse_usr_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usr_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usr_token().data(), this->usr_token().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.MeetMsg.usr_token"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_msg_seqs;
        break;
      }

      // optional sint64 msg_seqs = 10;
      case 10: {
        if (tag == 80) {
         parse_msg_seqs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &msg_seqs_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_mem_num;
        break;
      }

      // optional sint32 mem_num = 11;
      case 11: {
        if (tag == 88) {
         parse_mem_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &mem_num_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_usr_toto;
        break;
      }

      // optional .pms.ToUser usr_toto = 12;
      case 12: {
        if (tag == 98) {
         parse_usr_toto:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_usr_toto()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pms.MeetMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pms.MeetMsg)
  return false;
#undef DO_
}

void MeetMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pms.MeetMsg)
  // optional .pms.EMsgHead msg_head = 1;
  if (this->msg_head() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msg_head(), output);
  }

  // optional .pms.EMsgTag msg_tag = 2;
  if (this->msg_tag() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->msg_tag(), output);
  }

  // optional .pms.EMsgType msg_type = 3;
  if (this->msg_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->msg_type(), output);
  }

  // optional string usr_from = 4;
  if (this->usr_from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_from().data(), this->usr_from().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.MeetMsg.usr_from");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->usr_from(), output);
  }

  // optional string msg_cont = 5;
  if (this->msg_cont().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg_cont().data(), this->msg_cont().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.MeetMsg.msg_cont");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->msg_cont(), output);
  }

  // optional string rom_id = 6;
  if (this->rom_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->rom_id().data(), this->rom_id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.MeetMsg.rom_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->rom_id(), output);
  }

  // optional string rom_name = 7;
  if (this->rom_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->rom_name().data(), this->rom_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.MeetMsg.rom_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->rom_name(), output);
  }

  // optional string nck_name = 8;
  if (this->nck_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nck_name().data(), this->nck_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.MeetMsg.nck_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->nck_name(), output);
  }

  // optional string usr_token = 9;
  if (this->usr_token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usr_token().data(), this->usr_token().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.MeetMsg.usr_token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->usr_token(), output);
  }

  // optional sint64 msg_seqs = 10;
  if (this->msg_seqs() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(10, this->msg_seqs(), output);
  }

  // optional sint32 mem_num = 11;
  if (this->mem_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(11, this->mem_num(), output);
  }

  // optional .pms.ToUser usr_toto = 12;
  if (this->has_usr_toto()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      12, *this->usr_toto_, output);
  }

  // @@protoc_insertion_point(serialize_end:pms.MeetMsg)
}

int MeetMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pms.MeetMsg)
  int total_size = 0;

  // optional .pms.EMsgHead msg_head = 1;
  if (this->msg_head() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->msg_head());
  }

  // optional .pms.EMsgTag msg_tag = 2;
  if (this->msg_tag() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->msg_tag());
  }

  // optional .pms.EMsgType msg_type = 3;
  if (this->msg_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->msg_type());
  }

  // optional string usr_from = 4;
  if (this->usr_from().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_from());
  }

  // optional string msg_cont = 5;
  if (this->msg_cont().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg_cont());
  }

  // optional string rom_id = 6;
  if (this->rom_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->rom_id());
  }

  // optional string rom_name = 7;
  if (this->rom_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->rom_name());
  }

  // optional string nck_name = 8;
  if (this->nck_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nck_name());
  }

  // optional string usr_token = 9;
  if (this->usr_token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usr_token());
  }

  // optional sint64 msg_seqs = 10;
  if (this->msg_seqs() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt64Size(
        this->msg_seqs());
  }

  // optional sint32 mem_num = 11;
  if (this->mem_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->mem_num());
  }

  // optional .pms.ToUser usr_toto = 12;
  if (this->has_usr_toto()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->usr_toto_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MeetMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MeetMsg*>(&from));
}

void MeetMsg::MergeFrom(const MeetMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pms.MeetMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.msg_head() != 0) {
    set_msg_head(from.msg_head());
  }
  if (from.msg_tag() != 0) {
    set_msg_tag(from.msg_tag());
  }
  if (from.msg_type() != 0) {
    set_msg_type(from.msg_type());
  }
  if (from.usr_from().size() > 0) {

    usr_from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_from_);
  }
  if (from.msg_cont().size() > 0) {

    msg_cont_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_cont_);
  }
  if (from.rom_id().size() > 0) {

    rom_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rom_id_);
  }
  if (from.rom_name().size() > 0) {

    rom_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rom_name_);
  }
  if (from.nck_name().size() > 0) {

    nck_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nck_name_);
  }
  if (from.usr_token().size() > 0) {

    usr_token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usr_token_);
  }
  if (from.msg_seqs() != 0) {
    set_msg_seqs(from.msg_seqs());
  }
  if (from.mem_num() != 0) {
    set_mem_num(from.mem_num());
  }
  if (from.has_usr_toto()) {
    mutable_usr_toto()->::pms::ToUser::MergeFrom(from.usr_toto());
  }
}

void MeetMsg::CopyFrom(const MeetMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pms.MeetMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MeetMsg::IsInitialized() const {

  return true;
}

void MeetMsg::Swap(MeetMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MeetMsg::InternalSwap(MeetMsg* other) {
  std::swap(msg_head_, other->msg_head_);
  std::swap(msg_tag_, other->msg_tag_);
  std::swap(msg_type_, other->msg_type_);
  usr_from_.Swap(&other->usr_from_);
  msg_cont_.Swap(&other->msg_cont_);
  rom_id_.Swap(&other->rom_id_);
  rom_name_.Swap(&other->rom_name_);
  nck_name_.Swap(&other->nck_name_);
  usr_token_.Swap(&other->usr_token_);
  std::swap(msg_seqs_, other->msg_seqs_);
  std::swap(mem_num_, other->mem_num_);
  std::swap(usr_toto_, other->usr_toto_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MeetMsg::GetTypeName() const {
  return "pms.MeetMsg";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MeetMsg

// optional .pms.EMsgHead msg_head = 1;
void MeetMsg::clear_msg_head() {
  msg_head_ = 0;
}
 ::pms::EMsgHead MeetMsg::msg_head() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.msg_head)
  return static_cast< ::pms::EMsgHead >(msg_head_);
}
 void MeetMsg::set_msg_head(::pms::EMsgHead value) {
  
  msg_head_ = value;
  // @@protoc_insertion_point(field_set:pms.MeetMsg.msg_head)
}

// optional .pms.EMsgTag msg_tag = 2;
void MeetMsg::clear_msg_tag() {
  msg_tag_ = 0;
}
 ::pms::EMsgTag MeetMsg::msg_tag() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.msg_tag)
  return static_cast< ::pms::EMsgTag >(msg_tag_);
}
 void MeetMsg::set_msg_tag(::pms::EMsgTag value) {
  
  msg_tag_ = value;
  // @@protoc_insertion_point(field_set:pms.MeetMsg.msg_tag)
}

// optional .pms.EMsgType msg_type = 3;
void MeetMsg::clear_msg_type() {
  msg_type_ = 0;
}
 ::pms::EMsgType MeetMsg::msg_type() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.msg_type)
  return static_cast< ::pms::EMsgType >(msg_type_);
}
 void MeetMsg::set_msg_type(::pms::EMsgType value) {
  
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:pms.MeetMsg.msg_type)
}

// optional string usr_from = 4;
void MeetMsg::clear_usr_from() {
  usr_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MeetMsg::usr_from() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.usr_from)
  return usr_from_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_usr_from(const ::std::string& value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.MeetMsg.usr_from)
}
 void MeetMsg::set_usr_from(const char* value) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.MeetMsg.usr_from)
}
 void MeetMsg::set_usr_from(const char* value, size_t size) {
  
  usr_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.MeetMsg.usr_from)
}
 ::std::string* MeetMsg::mutable_usr_from() {
  
  // @@protoc_insertion_point(field_mutable:pms.MeetMsg.usr_from)
  return usr_from_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MeetMsg::release_usr_from() {
  // @@protoc_insertion_point(field_release:pms.MeetMsg.usr_from)
  
  return usr_from_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_allocated_usr_from(::std::string* usr_from) {
  if (usr_from != NULL) {
    
  } else {
    
  }
  usr_from_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_from);
  // @@protoc_insertion_point(field_set_allocated:pms.MeetMsg.usr_from)
}

// optional string msg_cont = 5;
void MeetMsg::clear_msg_cont() {
  msg_cont_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MeetMsg::msg_cont() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.msg_cont)
  return msg_cont_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_msg_cont(const ::std::string& value) {
  
  msg_cont_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.MeetMsg.msg_cont)
}
 void MeetMsg::set_msg_cont(const char* value) {
  
  msg_cont_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.MeetMsg.msg_cont)
}
 void MeetMsg::set_msg_cont(const char* value, size_t size) {
  
  msg_cont_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.MeetMsg.msg_cont)
}
 ::std::string* MeetMsg::mutable_msg_cont() {
  
  // @@protoc_insertion_point(field_mutable:pms.MeetMsg.msg_cont)
  return msg_cont_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MeetMsg::release_msg_cont() {
  // @@protoc_insertion_point(field_release:pms.MeetMsg.msg_cont)
  
  return msg_cont_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_allocated_msg_cont(::std::string* msg_cont) {
  if (msg_cont != NULL) {
    
  } else {
    
  }
  msg_cont_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg_cont);
  // @@protoc_insertion_point(field_set_allocated:pms.MeetMsg.msg_cont)
}

// optional string rom_id = 6;
void MeetMsg::clear_rom_id() {
  rom_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MeetMsg::rom_id() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.rom_id)
  return rom_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_rom_id(const ::std::string& value) {
  
  rom_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.MeetMsg.rom_id)
}
 void MeetMsg::set_rom_id(const char* value) {
  
  rom_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.MeetMsg.rom_id)
}
 void MeetMsg::set_rom_id(const char* value, size_t size) {
  
  rom_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.MeetMsg.rom_id)
}
 ::std::string* MeetMsg::mutable_rom_id() {
  
  // @@protoc_insertion_point(field_mutable:pms.MeetMsg.rom_id)
  return rom_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MeetMsg::release_rom_id() {
  // @@protoc_insertion_point(field_release:pms.MeetMsg.rom_id)
  
  return rom_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_allocated_rom_id(::std::string* rom_id) {
  if (rom_id != NULL) {
    
  } else {
    
  }
  rom_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rom_id);
  // @@protoc_insertion_point(field_set_allocated:pms.MeetMsg.rom_id)
}

// optional string rom_name = 7;
void MeetMsg::clear_rom_name() {
  rom_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MeetMsg::rom_name() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.rom_name)
  return rom_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_rom_name(const ::std::string& value) {
  
  rom_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.MeetMsg.rom_name)
}
 void MeetMsg::set_rom_name(const char* value) {
  
  rom_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.MeetMsg.rom_name)
}
 void MeetMsg::set_rom_name(const char* value, size_t size) {
  
  rom_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.MeetMsg.rom_name)
}
 ::std::string* MeetMsg::mutable_rom_name() {
  
  // @@protoc_insertion_point(field_mutable:pms.MeetMsg.rom_name)
  return rom_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MeetMsg::release_rom_name() {
  // @@protoc_insertion_point(field_release:pms.MeetMsg.rom_name)
  
  return rom_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_allocated_rom_name(::std::string* rom_name) {
  if (rom_name != NULL) {
    
  } else {
    
  }
  rom_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rom_name);
  // @@protoc_insertion_point(field_set_allocated:pms.MeetMsg.rom_name)
}

// optional string nck_name = 8;
void MeetMsg::clear_nck_name() {
  nck_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MeetMsg::nck_name() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.nck_name)
  return nck_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_nck_name(const ::std::string& value) {
  
  nck_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.MeetMsg.nck_name)
}
 void MeetMsg::set_nck_name(const char* value) {
  
  nck_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.MeetMsg.nck_name)
}
 void MeetMsg::set_nck_name(const char* value, size_t size) {
  
  nck_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.MeetMsg.nck_name)
}
 ::std::string* MeetMsg::mutable_nck_name() {
  
  // @@protoc_insertion_point(field_mutable:pms.MeetMsg.nck_name)
  return nck_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MeetMsg::release_nck_name() {
  // @@protoc_insertion_point(field_release:pms.MeetMsg.nck_name)
  
  return nck_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_allocated_nck_name(::std::string* nck_name) {
  if (nck_name != NULL) {
    
  } else {
    
  }
  nck_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nck_name);
  // @@protoc_insertion_point(field_set_allocated:pms.MeetMsg.nck_name)
}

// optional string usr_token = 9;
void MeetMsg::clear_usr_token() {
  usr_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MeetMsg::usr_token() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.usr_token)
  return usr_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_usr_token(const ::std::string& value) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.MeetMsg.usr_token)
}
 void MeetMsg::set_usr_token(const char* value) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.MeetMsg.usr_token)
}
 void MeetMsg::set_usr_token(const char* value, size_t size) {
  
  usr_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.MeetMsg.usr_token)
}
 ::std::string* MeetMsg::mutable_usr_token() {
  
  // @@protoc_insertion_point(field_mutable:pms.MeetMsg.usr_token)
  return usr_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MeetMsg::release_usr_token() {
  // @@protoc_insertion_point(field_release:pms.MeetMsg.usr_token)
  
  return usr_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MeetMsg::set_allocated_usr_token(::std::string* usr_token) {
  if (usr_token != NULL) {
    
  } else {
    
  }
  usr_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usr_token);
  // @@protoc_insertion_point(field_set_allocated:pms.MeetMsg.usr_token)
}

// optional sint64 msg_seqs = 10;
void MeetMsg::clear_msg_seqs() {
  msg_seqs_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 MeetMsg::msg_seqs() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.msg_seqs)
  return msg_seqs_;
}
 void MeetMsg::set_msg_seqs(::google::protobuf::int64 value) {
  
  msg_seqs_ = value;
  // @@protoc_insertion_point(field_set:pms.MeetMsg.msg_seqs)
}

// optional sint32 mem_num = 11;
void MeetMsg::clear_mem_num() {
  mem_num_ = 0;
}
 ::google::protobuf::int32 MeetMsg::mem_num() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.mem_num)
  return mem_num_;
}
 void MeetMsg::set_mem_num(::google::protobuf::int32 value) {
  
  mem_num_ = value;
  // @@protoc_insertion_point(field_set:pms.MeetMsg.mem_num)
}

// optional .pms.ToUser usr_toto = 12;
bool MeetMsg::has_usr_toto() const {
  return !_is_default_instance_ && usr_toto_ != NULL;
}
void MeetMsg::clear_usr_toto() {
  if (GetArenaNoVirtual() == NULL && usr_toto_ != NULL) delete usr_toto_;
  usr_toto_ = NULL;
}
const ::pms::ToUser& MeetMsg::usr_toto() const {
  // @@protoc_insertion_point(field_get:pms.MeetMsg.usr_toto)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return usr_toto_ != NULL ? *usr_toto_ : *default_instance().usr_toto_;
#else
  return usr_toto_ != NULL ? *usr_toto_ : *default_instance_->usr_toto_;
#endif
}
::pms::ToUser* MeetMsg::mutable_usr_toto() {
  
  if (usr_toto_ == NULL) {
    usr_toto_ = new ::pms::ToUser;
  }
  // @@protoc_insertion_point(field_mutable:pms.MeetMsg.usr_toto)
  return usr_toto_;
}
::pms::ToUser* MeetMsg::release_usr_toto() {
  // @@protoc_insertion_point(field_release:pms.MeetMsg.usr_toto)
  
  ::pms::ToUser* temp = usr_toto_;
  usr_toto_ = NULL;
  return temp;
}
void MeetMsg::set_allocated_usr_toto(::pms::ToUser* usr_toto) {
  delete usr_toto_;
  usr_toto_ = usr_toto;
  if (usr_toto) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:pms.MeetMsg.usr_toto)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pms

// @@protoc_insertion_point(global_scope)
