// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "storage_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace pms {

void protobuf_ShutdownFile_storage_5fmsg_2eproto() {
  delete StorageMsg::default_instance_;
  delete PackedStoreMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_storage_5fmsg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_storage_5fmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::pms::protobuf_AddDesc_storage_5fmsg_5ftype_2eproto();
  ::pms::protobuf_AddDesc_common_5fmsg_2eproto();
  StorageMsg::default_instance_ = new StorageMsg();
  PackedStoreMsg::default_instance_ = new PackedStoreMsg();
  StorageMsg::default_instance_->InitAsDefaultInstance();
  PackedStoreMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_storage_5fmsg_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_storage_5fmsg_2eproto_once_);
void protobuf_AddDesc_storage_5fmsg_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_storage_5fmsg_2eproto_once_,
                 &protobuf_AddDesc_storage_5fmsg_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_storage_5fmsg_2eproto {
  StaticDescriptorInitializer_storage_5fmsg_2eproto() {
    protobuf_AddDesc_storage_5fmsg_2eproto();
  }
} static_descriptor_initializer_storage_5fmsg_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StorageMsg::kRsvrcmdFieldNumber;
const int StorageMsg::kTsvrcmdFieldNumber;
const int StorageMsg::kMtagFieldNumber;
const int StorageMsg::kMflagFieldNumber;
const int StorageMsg::kMroleFieldNumber;
const int StorageMsg::kResultFieldNumber;
const int StorageMsg::kSequenceFieldNumber;
const int StorageMsg::kMaxseqnFieldNumber;
const int StorageMsg::kMsgidFieldNumber;
const int StorageMsg::kStoreidFieldNumber;
const int StorageMsg::kRuseridFieldNumber;
const int StorageMsg::kGroupidFieldNumber;
const int StorageMsg::kContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StorageMsg::StorageMsg()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pms.StorageMsg)
}

void StorageMsg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

StorageMsg::StorageMsg(const StorageMsg& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pms.StorageMsg)
}

void StorageMsg::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  rsvrcmd_ = 0;
  tsvrcmd_ = 0;
  mtag_ = 0;
  mflag_ = 0;
  mrole_ = 0;
  result_ = 0;
  sequence_ = GOOGLE_LONGLONG(0);
  maxseqn_ = GOOGLE_LONGLONG(0);
  msgid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  storeid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ruserid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  groupid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

StorageMsg::~StorageMsg() {
  // @@protoc_insertion_point(destructor:pms.StorageMsg)
  SharedDtor();
}

void StorageMsg::SharedDtor() {
  msgid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  storeid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ruserid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  groupid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void StorageMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const StorageMsg& StorageMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_storage_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_storage_5fmsg_2eproto();
#endif
  return *default_instance_;
}

StorageMsg* StorageMsg::default_instance_ = NULL;

StorageMsg* StorageMsg::New(::google::protobuf::Arena* arena) const {
  StorageMsg* n = new StorageMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StorageMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:pms.StorageMsg)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(StorageMsg, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<StorageMsg*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(rsvrcmd_, maxseqn_);
  msgid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  storeid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ruserid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  groupid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool StorageMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pms.StorageMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .pms.EServerCmd rsvrcmd = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_rsvrcmd(static_cast< ::pms::EServerCmd >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_tsvrcmd;
        break;
      }

      // optional .pms.EServerCmd tsvrcmd = 2;
      case 2: {
        if (tag == 16) {
         parse_tsvrcmd:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_tsvrcmd(static_cast< ::pms::EServerCmd >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_mtag;
        break;
      }

      // optional .pms.EStorageTag mtag = 3;
      case 3: {
        if (tag == 24) {
         parse_mtag:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_mtag(static_cast< ::pms::EStorageTag >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_mflag;
        break;
      }

      // optional .pms.EMsgFlag mflag = 4;
      case 4: {
        if (tag == 32) {
         parse_mflag:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_mflag(static_cast< ::pms::EMsgFlag >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_mrole;
        break;
      }

      // optional .pms.EMsgRole mrole = 5;
      case 5: {
        if (tag == 40) {
         parse_mrole:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_mrole(static_cast< ::pms::EMsgRole >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_result;
        break;
      }

      // optional sint32 result = 6;
      case 6: {
        if (tag == 48) {
         parse_result:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &result_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_sequence;
        break;
      }

      // optional sint64 sequence = 7;
      case 7: {
        if (tag == 56) {
         parse_sequence:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &sequence_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_maxseqn;
        break;
      }

      // optional sint64 maxseqn = 8;
      case 8: {
        if (tag == 64) {
         parse_maxseqn:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &maxseqn_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_msgid;
        break;
      }

      // optional string msgid = 9;
      case 9: {
        if (tag == 74) {
         parse_msgid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msgid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msgid().data(), this->msgid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.StorageMsg.msgid"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_storeid;
        break;
      }

      // optional string storeid = 10;
      case 10: {
        if (tag == 82) {
         parse_storeid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_storeid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->storeid().data(), this->storeid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.StorageMsg.storeid"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_ruserid;
        break;
      }

      // optional string ruserid = 11;
      case 11: {
        if (tag == 90) {
         parse_ruserid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ruserid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ruserid().data(), this->ruserid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.StorageMsg.ruserid"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_groupid;
        break;
      }

      // optional string groupid = 12;
      case 12: {
        if (tag == 98) {
         parse_groupid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_groupid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->groupid().data(), this->groupid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pms.StorageMsg.groupid"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_content;
        break;
      }

      // optional bytes content = 13;
      case 13: {
        if (tag == 106) {
         parse_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_content()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pms.StorageMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pms.StorageMsg)
  return false;
#undef DO_
}

void StorageMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pms.StorageMsg)
  // optional .pms.EServerCmd rsvrcmd = 1;
  if (this->rsvrcmd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->rsvrcmd(), output);
  }

  // optional .pms.EServerCmd tsvrcmd = 2;
  if (this->tsvrcmd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->tsvrcmd(), output);
  }

  // optional .pms.EStorageTag mtag = 3;
  if (this->mtag() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->mtag(), output);
  }

  // optional .pms.EMsgFlag mflag = 4;
  if (this->mflag() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->mflag(), output);
  }

  // optional .pms.EMsgRole mrole = 5;
  if (this->mrole() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->mrole(), output);
  }

  // optional sint32 result = 6;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(6, this->result(), output);
  }

  // optional sint64 sequence = 7;
  if (this->sequence() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(7, this->sequence(), output);
  }

  // optional sint64 maxseqn = 8;
  if (this->maxseqn() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(8, this->maxseqn(), output);
  }

  // optional string msgid = 9;
  if (this->msgid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msgid().data(), this->msgid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.StorageMsg.msgid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->msgid(), output);
  }

  // optional string storeid = 10;
  if (this->storeid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->storeid().data(), this->storeid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.StorageMsg.storeid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->storeid(), output);
  }

  // optional string ruserid = 11;
  if (this->ruserid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ruserid().data(), this->ruserid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.StorageMsg.ruserid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->ruserid(), output);
  }

  // optional string groupid = 12;
  if (this->groupid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->groupid().data(), this->groupid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pms.StorageMsg.groupid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->groupid(), output);
  }

  // optional bytes content = 13;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      13, this->content(), output);
  }

  // @@protoc_insertion_point(serialize_end:pms.StorageMsg)
}

int StorageMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pms.StorageMsg)
  int total_size = 0;

  // optional .pms.EServerCmd rsvrcmd = 1;
  if (this->rsvrcmd() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->rsvrcmd());
  }

  // optional .pms.EServerCmd tsvrcmd = 2;
  if (this->tsvrcmd() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->tsvrcmd());
  }

  // optional .pms.EStorageTag mtag = 3;
  if (this->mtag() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->mtag());
  }

  // optional .pms.EMsgFlag mflag = 4;
  if (this->mflag() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->mflag());
  }

  // optional .pms.EMsgRole mrole = 5;
  if (this->mrole() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->mrole());
  }

  // optional sint32 result = 6;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->result());
  }

  // optional sint64 sequence = 7;
  if (this->sequence() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt64Size(
        this->sequence());
  }

  // optional sint64 maxseqn = 8;
  if (this->maxseqn() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt64Size(
        this->maxseqn());
  }

  // optional string msgid = 9;
  if (this->msgid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msgid());
  }

  // optional string storeid = 10;
  if (this->storeid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->storeid());
  }

  // optional string ruserid = 11;
  if (this->ruserid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ruserid());
  }

  // optional string groupid = 12;
  if (this->groupid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->groupid());
  }

  // optional bytes content = 13;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->content());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StorageMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const StorageMsg*>(&from));
}

void StorageMsg::MergeFrom(const StorageMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pms.StorageMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.rsvrcmd() != 0) {
    set_rsvrcmd(from.rsvrcmd());
  }
  if (from.tsvrcmd() != 0) {
    set_tsvrcmd(from.tsvrcmd());
  }
  if (from.mtag() != 0) {
    set_mtag(from.mtag());
  }
  if (from.mflag() != 0) {
    set_mflag(from.mflag());
  }
  if (from.mrole() != 0) {
    set_mrole(from.mrole());
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
  if (from.sequence() != 0) {
    set_sequence(from.sequence());
  }
  if (from.maxseqn() != 0) {
    set_maxseqn(from.maxseqn());
  }
  if (from.msgid().size() > 0) {

    msgid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgid_);
  }
  if (from.storeid().size() > 0) {

    storeid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.storeid_);
  }
  if (from.ruserid().size() > 0) {

    ruserid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ruserid_);
  }
  if (from.groupid().size() > 0) {

    groupid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.groupid_);
  }
  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
}

void StorageMsg::CopyFrom(const StorageMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pms.StorageMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StorageMsg::IsInitialized() const {

  return true;
}

void StorageMsg::Swap(StorageMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StorageMsg::InternalSwap(StorageMsg* other) {
  std::swap(rsvrcmd_, other->rsvrcmd_);
  std::swap(tsvrcmd_, other->tsvrcmd_);
  std::swap(mtag_, other->mtag_);
  std::swap(mflag_, other->mflag_);
  std::swap(mrole_, other->mrole_);
  std::swap(result_, other->result_);
  std::swap(sequence_, other->sequence_);
  std::swap(maxseqn_, other->maxseqn_);
  msgid_.Swap(&other->msgid_);
  storeid_.Swap(&other->storeid_);
  ruserid_.Swap(&other->ruserid_);
  groupid_.Swap(&other->groupid_);
  content_.Swap(&other->content_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string StorageMsg::GetTypeName() const {
  return "pms.StorageMsg";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StorageMsg

// optional .pms.EServerCmd rsvrcmd = 1;
void StorageMsg::clear_rsvrcmd() {
  rsvrcmd_ = 0;
}
 ::pms::EServerCmd StorageMsg::rsvrcmd() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.rsvrcmd)
  return static_cast< ::pms::EServerCmd >(rsvrcmd_);
}
 void StorageMsg::set_rsvrcmd(::pms::EServerCmd value) {
  
  rsvrcmd_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.rsvrcmd)
}

// optional .pms.EServerCmd tsvrcmd = 2;
void StorageMsg::clear_tsvrcmd() {
  tsvrcmd_ = 0;
}
 ::pms::EServerCmd StorageMsg::tsvrcmd() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.tsvrcmd)
  return static_cast< ::pms::EServerCmd >(tsvrcmd_);
}
 void StorageMsg::set_tsvrcmd(::pms::EServerCmd value) {
  
  tsvrcmd_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.tsvrcmd)
}

// optional .pms.EStorageTag mtag = 3;
void StorageMsg::clear_mtag() {
  mtag_ = 0;
}
 ::pms::EStorageTag StorageMsg::mtag() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.mtag)
  return static_cast< ::pms::EStorageTag >(mtag_);
}
 void StorageMsg::set_mtag(::pms::EStorageTag value) {
  
  mtag_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.mtag)
}

// optional .pms.EMsgFlag mflag = 4;
void StorageMsg::clear_mflag() {
  mflag_ = 0;
}
 ::pms::EMsgFlag StorageMsg::mflag() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.mflag)
  return static_cast< ::pms::EMsgFlag >(mflag_);
}
 void StorageMsg::set_mflag(::pms::EMsgFlag value) {
  
  mflag_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.mflag)
}

// optional .pms.EMsgRole mrole = 5;
void StorageMsg::clear_mrole() {
  mrole_ = 0;
}
 ::pms::EMsgRole StorageMsg::mrole() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.mrole)
  return static_cast< ::pms::EMsgRole >(mrole_);
}
 void StorageMsg::set_mrole(::pms::EMsgRole value) {
  
  mrole_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.mrole)
}

// optional sint32 result = 6;
void StorageMsg::clear_result() {
  result_ = 0;
}
 ::google::protobuf::int32 StorageMsg::result() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.result)
  return result_;
}
 void StorageMsg::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.result)
}

// optional sint64 sequence = 7;
void StorageMsg::clear_sequence() {
  sequence_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 StorageMsg::sequence() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.sequence)
  return sequence_;
}
 void StorageMsg::set_sequence(::google::protobuf::int64 value) {
  
  sequence_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.sequence)
}

// optional sint64 maxseqn = 8;
void StorageMsg::clear_maxseqn() {
  maxseqn_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 StorageMsg::maxseqn() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.maxseqn)
  return maxseqn_;
}
 void StorageMsg::set_maxseqn(::google::protobuf::int64 value) {
  
  maxseqn_ = value;
  // @@protoc_insertion_point(field_set:pms.StorageMsg.maxseqn)
}

// optional string msgid = 9;
void StorageMsg::clear_msgid() {
  msgid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& StorageMsg::msgid() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.msgid)
  return msgid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_msgid(const ::std::string& value) {
  
  msgid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.StorageMsg.msgid)
}
 void StorageMsg::set_msgid(const char* value) {
  
  msgid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.StorageMsg.msgid)
}
 void StorageMsg::set_msgid(const char* value, size_t size) {
  
  msgid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.StorageMsg.msgid)
}
 ::std::string* StorageMsg::mutable_msgid() {
  
  // @@protoc_insertion_point(field_mutable:pms.StorageMsg.msgid)
  return msgid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* StorageMsg::release_msgid() {
  // @@protoc_insertion_point(field_release:pms.StorageMsg.msgid)
  
  return msgid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_allocated_msgid(::std::string* msgid) {
  if (msgid != NULL) {
    
  } else {
    
  }
  msgid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msgid);
  // @@protoc_insertion_point(field_set_allocated:pms.StorageMsg.msgid)
}

// optional string storeid = 10;
void StorageMsg::clear_storeid() {
  storeid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& StorageMsg::storeid() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.storeid)
  return storeid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_storeid(const ::std::string& value) {
  
  storeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.StorageMsg.storeid)
}
 void StorageMsg::set_storeid(const char* value) {
  
  storeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.StorageMsg.storeid)
}
 void StorageMsg::set_storeid(const char* value, size_t size) {
  
  storeid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.StorageMsg.storeid)
}
 ::std::string* StorageMsg::mutable_storeid() {
  
  // @@protoc_insertion_point(field_mutable:pms.StorageMsg.storeid)
  return storeid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* StorageMsg::release_storeid() {
  // @@protoc_insertion_point(field_release:pms.StorageMsg.storeid)
  
  return storeid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_allocated_storeid(::std::string* storeid) {
  if (storeid != NULL) {
    
  } else {
    
  }
  storeid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), storeid);
  // @@protoc_insertion_point(field_set_allocated:pms.StorageMsg.storeid)
}

// optional string ruserid = 11;
void StorageMsg::clear_ruserid() {
  ruserid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& StorageMsg::ruserid() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.ruserid)
  return ruserid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_ruserid(const ::std::string& value) {
  
  ruserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.StorageMsg.ruserid)
}
 void StorageMsg::set_ruserid(const char* value) {
  
  ruserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.StorageMsg.ruserid)
}
 void StorageMsg::set_ruserid(const char* value, size_t size) {
  
  ruserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.StorageMsg.ruserid)
}
 ::std::string* StorageMsg::mutable_ruserid() {
  
  // @@protoc_insertion_point(field_mutable:pms.StorageMsg.ruserid)
  return ruserid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* StorageMsg::release_ruserid() {
  // @@protoc_insertion_point(field_release:pms.StorageMsg.ruserid)
  
  return ruserid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_allocated_ruserid(::std::string* ruserid) {
  if (ruserid != NULL) {
    
  } else {
    
  }
  ruserid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ruserid);
  // @@protoc_insertion_point(field_set_allocated:pms.StorageMsg.ruserid)
}

// optional string groupid = 12;
void StorageMsg::clear_groupid() {
  groupid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& StorageMsg::groupid() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.groupid)
  return groupid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_groupid(const ::std::string& value) {
  
  groupid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.StorageMsg.groupid)
}
 void StorageMsg::set_groupid(const char* value) {
  
  groupid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.StorageMsg.groupid)
}
 void StorageMsg::set_groupid(const char* value, size_t size) {
  
  groupid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.StorageMsg.groupid)
}
 ::std::string* StorageMsg::mutable_groupid() {
  
  // @@protoc_insertion_point(field_mutable:pms.StorageMsg.groupid)
  return groupid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* StorageMsg::release_groupid() {
  // @@protoc_insertion_point(field_release:pms.StorageMsg.groupid)
  
  return groupid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_allocated_groupid(::std::string* groupid) {
  if (groupid != NULL) {
    
  } else {
    
  }
  groupid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), groupid);
  // @@protoc_insertion_point(field_set_allocated:pms.StorageMsg.groupid)
}

// optional bytes content = 13;
void StorageMsg::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& StorageMsg::content() const {
  // @@protoc_insertion_point(field_get:pms.StorageMsg.content)
  return content_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pms.StorageMsg.content)
}
 void StorageMsg::set_content(const char* value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pms.StorageMsg.content)
}
 void StorageMsg::set_content(const void* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pms.StorageMsg.content)
}
 ::std::string* StorageMsg::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:pms.StorageMsg.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* StorageMsg::release_content() {
  // @@protoc_insertion_point(field_release:pms.StorageMsg.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StorageMsg::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:pms.StorageMsg.content)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PackedStoreMsg::kMsgsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PackedStoreMsg::PackedStoreMsg()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pms.PackedStoreMsg)
}

void PackedStoreMsg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PackedStoreMsg::PackedStoreMsg(const PackedStoreMsg& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pms.PackedStoreMsg)
}

void PackedStoreMsg::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

PackedStoreMsg::~PackedStoreMsg() {
  // @@protoc_insertion_point(destructor:pms.PackedStoreMsg)
  SharedDtor();
}

void PackedStoreMsg::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PackedStoreMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PackedStoreMsg& PackedStoreMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_storage_5fmsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_storage_5fmsg_2eproto();
#endif
  return *default_instance_;
}

PackedStoreMsg* PackedStoreMsg::default_instance_ = NULL;

PackedStoreMsg* PackedStoreMsg::New(::google::protobuf::Arena* arena) const {
  PackedStoreMsg* n = new PackedStoreMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PackedStoreMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:pms.PackedStoreMsg)
  msgs_.Clear();
}

bool PackedStoreMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pms.PackedStoreMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pms.StorageMsg msgs = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_msgs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_msgs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_msgs;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pms.PackedStoreMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pms.PackedStoreMsg)
  return false;
#undef DO_
}

void PackedStoreMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pms.PackedStoreMsg)
  // repeated .pms.StorageMsg msgs = 1;
  for (unsigned int i = 0, n = this->msgs_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->msgs(i), output);
  }

  // @@protoc_insertion_point(serialize_end:pms.PackedStoreMsg)
}

int PackedStoreMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pms.PackedStoreMsg)
  int total_size = 0;

  // repeated .pms.StorageMsg msgs = 1;
  total_size += 1 * this->msgs_size();
  for (int i = 0; i < this->msgs_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->msgs(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PackedStoreMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PackedStoreMsg*>(&from));
}

void PackedStoreMsg::MergeFrom(const PackedStoreMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pms.PackedStoreMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  msgs_.MergeFrom(from.msgs_);
}

void PackedStoreMsg::CopyFrom(const PackedStoreMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pms.PackedStoreMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PackedStoreMsg::IsInitialized() const {

  return true;
}

void PackedStoreMsg::Swap(PackedStoreMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PackedStoreMsg::InternalSwap(PackedStoreMsg* other) {
  msgs_.UnsafeArenaSwap(&other->msgs_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string PackedStoreMsg::GetTypeName() const {
  return "pms.PackedStoreMsg";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PackedStoreMsg

// repeated .pms.StorageMsg msgs = 1;
int PackedStoreMsg::msgs_size() const {
  return msgs_.size();
}
void PackedStoreMsg::clear_msgs() {
  msgs_.Clear();
}
const ::pms::StorageMsg& PackedStoreMsg::msgs(int index) const {
  // @@protoc_insertion_point(field_get:pms.PackedStoreMsg.msgs)
  return msgs_.Get(index);
}
::pms::StorageMsg* PackedStoreMsg::mutable_msgs(int index) {
  // @@protoc_insertion_point(field_mutable:pms.PackedStoreMsg.msgs)
  return msgs_.Mutable(index);
}
::pms::StorageMsg* PackedStoreMsg::add_msgs() {
  // @@protoc_insertion_point(field_add:pms.PackedStoreMsg.msgs)
  return msgs_.Add();
}
::google::protobuf::RepeatedPtrField< ::pms::StorageMsg >*
PackedStoreMsg::mutable_msgs() {
  // @@protoc_insertion_point(field_mutable_list:pms.PackedStoreMsg.msgs)
  return &msgs_;
}
const ::google::protobuf::RepeatedPtrField< ::pms::StorageMsg >&
PackedStoreMsg::msgs() const {
  // @@protoc_insertion_point(field_list:pms.PackedStoreMsg.msgs)
  return msgs_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pms

// @@protoc_insertion_point(global_scope)
