// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_msg_type.proto

package pms;

public final class StorageMsgType {
  private StorageMsgType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   * the tag of storeage msg
   * </pre>
   *
   * Protobuf enum {@code pms.EStorageTag}
   */
  public enum EStorageTag
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>TSEQN = 0;</code>
     */
    TSEQN(0),
    /**
     * <code>TDATA = 1;</code>
     */
    TDATA(1),
    /**
     * <code>TFETCHSEQN = 2;</code>
     */
    TFETCHSEQN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TSEQN = 0;</code>
     */
    public static final int TSEQN_VALUE = 0;
    /**
     * <code>TDATA = 1;</code>
     */
    public static final int TDATA_VALUE = 1;
    /**
     * <code>TFETCHSEQN = 2;</code>
     */
    public static final int TFETCHSEQN_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EStorageTag valueOf(int value) {
      return forNumber(value);
    }

    public static EStorageTag forNumber(int value) {
      switch (value) {
        case 0: return TSEQN;
        case 1: return TDATA;
        case 2: return TFETCHSEQN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EStorageTag>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EStorageTag> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EStorageTag>() {
            public EStorageTag findValueByNumber(int number) {
              return EStorageTag.forNumber(number);
            }
          };

    private final int value;

    private EStorageTag(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pms.EStorageTag)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
